# Generated by Django 2.2.28 on 2022-10-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveFileRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(db_index=True, verbose_name='文件ID')),
                ('model_name', models.CharField(max_length=128, verbose_name='存储模型')),
                ('relation_id', models.IntegerField(verbose_name='关联模型ID')),
                ('field_name', models.CharField(max_length=128, verbose_name='存储字段')),
            ],
            options={
                'verbose_name': '文件关联管理',
                'verbose_name_plural': '文件关联管理',
                'index_together': {('model_name', 'field_name', 'relation_id')},
            },
        ),
    ]
