# Generated by Django 2.2.28 on 2023-08-11 00:15

import apps.vadmin.op_drf.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('role_name', models.CharField(max_length=16, verbose_name='角色名字')),
            ],
            options={
                'verbose_name': '示例角色表',
                'verbose_name_plural': '示例角色表',
                'db_table': 'case_case_role',
            },
        ),
        migrations.CreateModel(
            name='CaseMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='填写任务名称', max_length=256, verbose_name='任务名称')),
                ('plan', models.TextField(blank=True, help_text='填写执行计划', max_length=1024, null=True, verbose_name='执行计划')),
                ('employee_choice', models.CharField(choices=[('f', '正式'), ('u', '非正式')], default='f', max_length=1, verbose_name='员工类型')),
                ('multi_cities', models.CharField(blank=True, max_length=12, null=True, verbose_name='城市')),
                ('status', models.BooleanField(default=False, verbose_name='运行状态')),
                ('case_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.CaseRole', verbose_name='关联角色')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '示例主体表',
                'verbose_name_plural': '示例主体表',
                'db_table': 'case_case_main',
            },
        ),
    ]
